### ISSUE TITLE
Planet Generation Not Working

### ISSUE THREAD

**Issue by enrique-torres** [TheHunterJPScripts/Procedural-planet-generation#1]
Hi! I've been trying to use these scripts in Unity 2019, and the planet is only being generated into a sphere, without any mountains or any water. 

It's also giving me some NullReferenceExceptions when creating the planet because it looks like it's not generating every triangle from the planet for some reason.
`static public void InstantiateIntoWorld()
        {
            terrainInstantiated = true;
            // Instantiate the polygons into the scene while been added to the queue.
            while (polygonsToInstantiate.Count != 0)
            {
                Polygon poly = polygonsToInstantiate.Dequeue();
                poly.Instantiate();
                // Add it to the list for later modification.
                distanceList.Add(poly);
            }
        }`
This seems to be the function with problems. "poly" is sometimes null.

**Comment by enrique-torres** [comment]
A simple if (poly != null) seems to fix the issue and ends up generating the whole spherical planet. But still no elevation data is being generated. I'm trying to generate terraced planets

**Comment by TheHunterJPScripts** [comment]
It's being more or less a year since the last time i opened the project. I've been working on improving and changing the way to generate the planet that they are completly different projects. Anyways i will take a look se if i can make it work again.

Update: I just created a new project in 2018.3.8f1 and followed the instruccions on the readme and it works as expected. 
![alt text](https://i.gyazo.com/9b8363e7015d32fcfb6e4ce3b752d229.png)
If you prefer you can contact me via [Twitter](https://twitter.com/TheHunterJP), i check it more frequently. And if you can send me the error message so i can check exactly what went wrong.

**Comment by enrique-torres** [comment]
The error message was a NullPointerException on poly. I'm using Unity 2019 and it doesn't seem to work on the newest version. I'll follow you on Twitter and send you a message there

**Comment by TheHunterJPScripts** [comment]
Still work for me on 2019.1.11f1. What is the exact version you are using?

**Comment by enrique-torres** [comment]
2019.3.8f I think, or something like that. Could you post a version of the project working on 2019?

**Comment by TheHunterJPScripts** [comment]
The project work on 2019, i just tried it creating a new project on 2019.1.11f1 and it works. Could it be that a parameter if not set properly? You can try it by yourself and tell me if it works on your version: https://www.dropbox.com/s/krk43ervna8crn0/Project.zip?dl=0

**Comment by enrique-torres** [comment]
Thanks a lot, I'll try it later today. Really appreciate your effort!

**Comment by TheHunterJPScripts** [comment]
Let me know if it works.

**Comment by enrique-torres** [comment]
Works flawlessly! I don't know what I was doing wrong before. Awesome scripts by the way. Saludos desde Zaragoza ;)
